version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: palace_postgres
    restart: always
    environment:
      - POSTGRES_DB=palace_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
