import os
import polib

# Define the dictionary for Palace Karimi
translations = {
    'fa': {
        'Home': 'خانه', 'About Us': 'درباره ما', 'Products': 'محصولات', 'Contact Us': 'تماس با ما',
        'Get in Touch': 'در ارتباط باشید', 'Newsletter': 'خبرنامه',
        'Subscribe to our newsletter to get the latest updates and luxury offers.': 'برای دریافت آخرین به‌روزرسانی‌ها و پیشنهادات ویژه ما، در خبرنامه مشترک شوید.',
        'Success!': 'موفقیت!', 'You have been added to our email list.': 'شما به لیست ایمیل ما افزوده شدید.',
        'Email Address': 'آدرس ایمیل', 'Subscribe': 'عضویت', 'Latest Tweets': 'جدیدترین توییت‌ها',
        'Please wait...': 'لطفا منتظر باشید ...', 'Tehran, Iran': 'تهران، ایران',
        'Follow Us': 'ما را دنبال کنید', '© 2026 Palace Karimi. All Rights Reserved.': '© 2026 پالس کریمی. تمامی حقوق محفوظ است.',
        'Designed & Developed by': 'طراحی و توسعه توسط', 'FAQ': 'سوالات متداول', 'Sitemap': 'نقشه سایت',
        'The Finest Quality': 'بهترین و باکیفیت‌ترین', 'PREMIUM SAFFRON': 'زعفران سوپر نگین', 'Experience the true taste of luxury.': 'طعم واقعی اصالت و لوکس بودن را تجربه کنید.', 'Exporting Worldwide': 'صادرات به سراسر جهان', 'PERSIAN PISTACHIO': 'پسته اصیل ایرانی', 'Hand-picked and premium quality.': 'دست‌چین شده و با کیفیت جهانی.', 'Palace Karimi': 'پالس کریمی', 'YOUR TRUSTED PARTNER': 'شریک معتمد شما', 'Providing the best agricultural products.': 'ارائه‌دهنده بهترین محصولات کشاورزی.',
        'Follow us on social media for the latest updates and news!': 'برای اطلاع از آخرین به روز رسانی ها و اخبار، ما را در شبکه های اجتماعی دنبال کنید!',
        'Experience a secure purchase with the top exporter of authentic Iranian products': 'تجربه خریدی مطمئن با صادرکننده برتر محصولات اصیل ایرانی', 'Demand the best quality saffron and pistachio from us.': 'بهترین کیفیت زعفران و پسته را از ما بخواهید.', 'Contact Experts': 'تماس با کارشناسان', 'or': 'یا', 'view products.': 'مشاهده محصولات.', 'Palace Karimi is a brand that is': 'پالس کریمی برندی', 'Authentic': 'اصیل', 'High Quality': 'باکیفیت', 'Global': 'جهانی', 'and a secure choice for export.': 'و انتخابی مطمئن برای صادرات است.', 'With years of experience in cultivation, processing, and exporting the finest Iranian saffron and pistachio, we offer quality and authenticity to global markets. All our products are packaged and shipped with international standards.': 'ما با سال‌ها تجربه در زمینه کشت، فرآوری و صادرات مرغوب‌ترین زعفران و پسته ایرانی، کیفیت و اصالت را به بازارهای جهانی عرضه می‌کنیم. تمامی محصولات ما با استانداردهای بین‌المللی بسته‌بندی و ارسال می‌شوند.',
        'Experience the pinnacle of luxury with Palace Karimi': 'اوج لوکس بودن را با پالس کریمی تجربه کنید', 'Consultation': 'مشاوره',
        'Harvesting': 'برداشت', 'Processing': 'فرآوری', 'Packaging': 'بسته‌بندی', 'Global Export': 'صادرات جهانی',
        'New': 'جدید', 'View Details': 'مشاهده جزئیات', 'No products available.': 'محصولی برای نمایش وجود ندارد.',
        'Why Choose': 'چرا انتخاب کنید', 'Palace Karimi?': 'پالاس کریمی؟', '100% Organic': '۱۰۰٪ ارگانیک', 'Pure, natural products cultivated without harmful chemicals.': 'محصولات خالص و طبیعی که بدون مواد شیمیایی مضر کشت می‌شوند.', 'Premium Quality': 'کیفیت برتر', 'Export-grade saffron and pistachio carefully hand-picked.': 'زعفران و پسته صادراتی با دقت دست‌چین شده.', 'Luxury Packaging': 'بسته‌بندی لوکس', 'Elegant and secure packaging maintaining freshness and aroma.': 'بسته‌بندی شیک و ایمن که تازگی و عطر را حفظ می‌کند.', 'Lab Certified': 'دارای گواهی آزمایشگاه', 'Rigorous laboratory testing for color, flavor, and purity.': 'آزمایش‌های دقیق آزمایشگاهی برای رنگ، طعم و خلوص.', 'Direct from Farms': 'مستقیم از مزارع', 'Sourced directly from the best Iranian agricultural lands.': 'تهیه شده مستقیم از بهترین زمین‌های کشاورزی ایران.', 'Wholesale Supply': 'تأمین عمده', 'Capability to fulfill bulk orders for businesses worldwide.': 'توانایی انجام سفارشات عمده برای کسب‌وکارهای سراسر جهان.', '24/7 Support': 'پشتیبانی ۲۴/۷', 'Dedicated customer service and consultation for our partners.': 'خدمات مشتری و مشاوره اختصاصی برای شرکای ما.', 'Our Guarantees': 'تضمین‌های ما', 'Authenticity Guarantee': 'تضمین اصالت', 'We guarantee that all our saffron and pistachios are 100% authentic Persian products, free from any artificial additives or coloring.': 'ما تضمین می‌کنیم که تمام زعفران و پسته‌های ما ۱۰۰٪ محصولات اصیل ایرانی و بدون هیچ‌گونه افزودنی یا رنگ مصنوعی هستند.', 'International Standards': 'استانداردهای بین‌المللی', 'Our products are processed and packaged strictly according to international food safety and hygiene standards.': 'محصولات ما کاملاً مطابق با استانداردهای بین‌المللی ایمنی و بهداشت مواد غذایی فرآوری و بسته‌بندی می‌شوند.', 'Custom White-Labeling': 'برچسب‌گذاری سفید سفارشی', 'We offer exclusive custom packaging and white-labeling services for your brand to stand out in the global market.': 'ما خدمات بسته‌بندی سفارشی و برچسب‌گذاری سفید انحصاری را برای برجسته شدن برند شما در بازار جهانی ارائه می‌دهیم.', 'We proudly export our products to': 'ما با افتخار محصولات خود را به', 'Europe': 'اروپا', 'Asia': 'آسیا', 'Middle East': 'خاورمیانه', 'Trusted by leading international businesses and distributors worldwide.': 'مورد اعتماد کسب‌وکارها و توزیع‌کنندگان برجسته بین‌المللی در سراسر جهان.'
    },
    'en': {
        'Home': 'Home', 'About Us': 'About Us', 'Products': 'Products', 'Contact Us': 'Contact Us',
        'Get in Touch': 'Get in Touch', 'Newsletter': 'Newsletter',
        'Subscribe to our newsletter to get the latest updates and luxury offers.': 'Subscribe to our newsletter to get the latest updates and luxury offers.',
        'Success!': 'Success!', 'You have been added to our email list.': 'You have been added to our email list.',
        'Email Address': 'Email Address', 'Subscribe': 'Subscribe', 'Latest Tweets': 'Latest Tweets',
        'Please wait...': 'Please wait...', 'Tehran, Iran': 'Tehran, Iran',
        'Follow Us': 'Follow Us', '© 2026 Palace Karimi. All Rights Reserved.': '© 2026 Palace Karimi. All Rights Reserved.',
        'Designed & Developed by': 'Designed & Developed by', 'FAQ': 'FAQ', 'Sitemap': 'Sitemap',
        'The Finest Quality': 'The Finest Quality', 'PREMIUM SAFFRON': 'PREMIUM SAFFRON', 'Experience the true taste of luxury.': 'Experience the true taste of luxury.', 'Exporting Worldwide': 'Exporting Worldwide', 'PERSIAN PISTACHIO': 'PERSIAN PISTACHIO', 'Hand-picked and premium quality.': 'Hand-picked and premium quality.', 'Palace Karimi': 'Palace Karimi', 'YOUR TRUSTED PARTNER': 'YOUR TRUSTED PARTNER', 'Providing the best agricultural products.': 'Providing the best agricultural products.',
        'Follow us on social media for the latest updates and news!': 'Follow us on social media for the latest updates and news!',
        'Experience a secure purchase with the top exporter of authentic Iranian products': 'Experience a secure purchase with the top exporter of authentic Iranian products', 'Demand the best quality saffron and pistachio from us.': 'Demand the best quality saffron and pistachio from us.', 'Contact Experts': 'Contact Experts', 'or': 'or', 'view products.': 'view products.', 'Palace Karimi is a brand that is': 'Palace Karimi is a brand that is', 'Authentic': 'Authentic', 'High Quality': 'High Quality', 'Global': 'Global', 'and a secure choice for export.': 'and a secure choice for export.', 'With years of experience in cultivation, processing, and exporting the finest Iranian saffron and pistachio, we offer quality and authenticity to global markets. All our products are packaged and shipped with international standards.': 'With years of experience in cultivation, processing, and exporting the finest Iranian saffron and pistachio, we offer quality and authenticity to global markets. All our products are packaged and shipped with international standards.',
        'Experience the pinnacle of luxury with Palace Karimi': 'Experience the pinnacle of luxury with Palace Karimi', 'Consultation': 'Consultation',
        'Harvesting': 'Harvesting', 'Processing': 'Processing', 'Packaging': 'Packaging', 'Global Export': 'Global Export',
        'New': 'New', 'View Details': 'View Details', 'No products available.': 'No products available.',
        'Why Choose': 'Why Choose', 'Palace Karimi?': 'Palace Karimi?', '100% Organic': '100% Organic', 'Pure, natural products cultivated without harmful chemicals.': 'Pure, natural products cultivated without harmful chemicals.', 'Premium Quality': 'Premium Quality', 'Export-grade saffron and pistachio carefully hand-picked.': 'Export-grade saffron and pistachio carefully hand-picked.', 'Luxury Packaging': 'Luxury Packaging', 'Elegant and secure packaging maintaining freshness and aroma.': 'Elegant and secure packaging maintaining freshness and aroma.', 'Lab Certified': 'Lab Certified', 'Rigorous laboratory testing for color, flavor, and purity.': 'Rigorous laboratory testing for color, flavor, and purity.', 'Direct from Farms': 'Direct from Farms', 'Sourced directly from the best Iranian agricultural lands.': 'Sourced directly from the best Iranian agricultural lands.', 'Wholesale Supply': 'Wholesale Supply', 'Capability to fulfill bulk orders for businesses worldwide.': 'Capability to fulfill bulk orders for businesses worldwide.', '24/7 Support': '24/7 Support', 'Dedicated customer service and consultation for our partners.': 'Dedicated customer service and consultation for our partners.', 'Our Guarantees': 'Our Guarantees', 'Authenticity Guarantee': 'Authenticity Guarantee', 'We guarantee that all our saffron and pistachios are 100% authentic Persian products, free from any artificial additives or coloring.': 'We guarantee that all our saffron and pistachios are 100% authentic Persian products, free from any artificial additives or coloring.', 'International Standards': 'International Standards', 'Our products are processed and packaged strictly according to international food safety and hygiene standards.': 'Our products are processed and packaged strictly according to international food safety and hygiene standards.', 'Custom White-Labeling': 'Custom White-Labeling', 'We offer exclusive custom packaging and white-labeling services for your brand to stand out in the global market.': 'We offer exclusive custom packaging and white-labeling services for your brand to stand out in the global market.', 'We proudly export our products to': 'We proudly export our products to', 'Europe': 'Europe', 'Asia': 'Asia', 'Middle East': 'Middle East', 'Trusted by leading international businesses and distributors worldwide.': 'Trusted by leading international businesses and distributors worldwide.'
    },
    'ar': {
        'Home': 'الرئيسية', 'About Us': 'معلومات عنا', 'Products': 'المنتجات', 'Contact Us': 'اتصل بنا',
        'Get in Touch': 'ابق على تواصل', 'Newsletter': 'النشرة الإخبارية',
        'Subscribe to our newsletter to get the latest updates and luxury offers.': 'اشترك في نشرتنا الإخبارية للحصول على أحدث التحديثات والعروض الفاخرة.',
        'Success!': 'نجاح!', 'You have been added to our email list.': 'تمت إضافتك إلى قائمة بريدنا الإلكتروني.',
        'Email Address': 'عنوان البريد الإلكتروني', 'Subscribe': 'اشتراك', 'Latest Tweets': 'أحدث التغريدات',
        'Please wait...': 'أرجو الإنتظار...', 'Tehran, Iran': 'طهران، إيران',
        'Follow Us': 'تابعنا', '© 2026 Palace Karimi. All Rights Reserved.': '© 2026 بالاس كريمي. كل الحقوق محفوظة.',
        'Designed & Developed by': 'تم التصميم والتطوير بواسطة', 'FAQ': 'الأسئلة الشائعة', 'Sitemap': 'خريطة الموقع',
        'The Finest Quality': 'أفضل جودة', 'PREMIUM SAFFRON': 'زعفران سوبر نيجين', 'Experience the true taste of luxury.': 'اكتشف الطعم الحقيقي للفخامة.', 'Exporting Worldwide': 'تصدير لجميع أنحاء العالم', 'PERSIAN PISTACHIO': 'فستق فارسي', 'Hand-picked and premium quality.': 'مقطوف يدوياً وبجودة عالية.', 'Palace Karimi': 'بالاس كريمي', 'YOUR TRUSTED PARTNER': 'شريكك الموثوق', 'Providing the best agricultural products.': 'نقدم أفضل المنتجات الزراعية.',
        'Follow us on social media for the latest updates and news!': 'تابعنا على وسائل التواصل الاجتماعي للحصول على آخر التحديثات والأخبار!',
        'Experience a secure purchase with the top exporter of authentic Iranian products': 'تجربة شراء آمنة مع أفضل مصدر للمنتجات الإيرانية الأصيلة', 'Demand the best quality saffron and pistachio from us.': 'اطلب منا أفضل جودة من الزعفران والفستق.', 'Contact Experts': 'اتصل بالخبراء', 'or': 'أو', 'view products.': 'عرض المنتجات.', 'Palace Karimi is a brand that is': 'بالاس كريمي هي علامة تجارية', 'Authentic': 'أصيلة', 'High Quality': 'عالية الجودة', 'Global': 'عالمية', 'and a secure choice for export.': 'وخيار آمن للتصدير.', 'With years of experience in cultivation, processing, and exporting the finest Iranian saffron and pistachio, we offer quality and authenticity to global markets. All our products are packaged and shipped with international standards.': 'بفضل سنوات من الخبرة في زراعة وتجهيز وتصدير أجود أنواع الزعفران والفستق الإيراني، نقدم الجودة والأصالة للأسواق العالمية. يتم تعبئة جميع منتجاتنا وشحنها وفقًا للمعايير الدولية.',
        'Experience the pinnacle of luxury with Palace Karimi': 'جرب قمة الفخامة مع بالاس كريمي', 'Consultation': 'استشارة',
        'Harvesting': 'حصاد', 'Processing': 'معالجة', 'Packaging': 'تغليف', 'Global Export': 'التصدير العالمي',
        'New': 'جديد', 'View Details': 'عرض التفاصيل', 'No products available.': 'لا توجد منتجات متاحة.',
        'Why Choose': 'لماذا تختار', 'Palace Karimi?': 'بالاس كريمي؟', '100% Organic': '٪١٠٠ عضوي', 'Pure, natural products cultivated without harmful chemicals.': 'منتجات نقية وطبيعية مزروعة بدون مواد كيميائية ضارة.', 'Premium Quality': 'جودة ممتازة', 'Export-grade saffron and pistachio carefully hand-picked.': 'زعفران وفستق من الدرجة التصديرية يتم انتقاؤه بعناية.', 'Luxury Packaging': 'تغليف فاخر', 'Elegant and secure packaging maintaining freshness and aroma.': 'تغليف أنيق وآمن يحافظ على النضارة والرائحة.', 'Lab Certified': 'معتمد من المختبر', 'Rigorous laboratory testing for color, flavor, and purity.': 'اختبارات معملية صارمة للون والنكهة والنقاء.', 'Direct from Farms': 'مباشرة من المزارع', 'Sourced directly from the best Iranian agricultural lands.': 'يتم الحصول عليها مباشرة من أفضل الأراضي الزراعية الإيرانية.', 'Wholesale Supply': 'توريد بالجملة', 'Capability to fulfill bulk orders for businesses worldwide.': 'القدرة على تلبية الطلبات الكبيرة للشركات في جميع أنحاء العالم.', '24/7 Support': 'دعم ٢٤/٧', 'Dedicated customer service and consultation for our partners.': 'خدمة عملاء واستشارات مخصصة لشركائنا.', 'Our Guarantees': 'ضماناتنا', 'Authenticity Guarantee': 'ضمان الأصالة', 'We guarantee that all our saffron and pistachios are 100% authentic Persian products, free from any artificial additives or coloring.': 'نحن نضمن أن جميع منتجاتنا من الزعفران والفستق هي منتجات فارسية أصلية ١٠٠٪، خالية من أي إضافات صناعية أو تلوين.', 'International Standards': 'المعايير الدولية', 'Our products are processed and packaged strictly according to international food safety and hygiene standards.': 'تتم معالجة منتجاتنا وتعبئتها بشكل صارم وفقًا لمعايير سلامة الأغذية والنظافة الدولية.', 'Custom White-Labeling': 'العلامة التجارية البيضاء المخصصة', 'We offer exclusive custom packaging and white-labeling services for your brand to stand out in the global market.': 'نحن نقدم خدمات تغليف مخصصة وحصرية ووضع العلامات التجارية البيضاء لعلامتك التجارية لتبرز في السوق العالمية.', 'We proudly export our products to': 'نحن نصدر منتجاتنا بفخر إلى', 'Europe': 'أوروبا', 'Asia': 'آسيا', 'Middle East': 'الشرق الأوسط', 'Trusted by leading international businesses and distributors worldwide.': 'موثوق به من قبل الشركات والموزعين الدوليين الرائدين في جميع أنحاء العالم.'
    },
    'tr': {
        'Home': 'Ana Sayfa', 'About Us': 'Hakkımızda', 'Products': 'Ürünler', 'Contact Us': 'İletişim',
        'Get in Touch': 'İletişimde Kalın', 'Newsletter': 'Bülten',
        'Subscribe to our newsletter to get the latest updates and luxury offers.': 'En son güncellemeleri ve lüks teklifleri almak için bültenimize abone olun.',
        'Success!': 'Başarılı!', 'You have been added to our email list.': 'E-posta listemize eklendiniz.',
        'Email Address': 'E-posta Adresi', 'Subscribe': 'Abone Ol', 'Latest Tweets': 'Son Tweetler',
        'Please wait...': 'Lütfen bekleyin...', 'Tehran, Iran': 'Tahran, İran',
        'Follow Us': 'Bizi Takip Edin', '© 2026 Palace Karimi. All Rights Reserved.': '© 2026 Palace Karimi. Tüm hakları saklıdır.',
        'Designed & Developed by': 'Tasarım ve Geliştirme:', 'FAQ': 'SSS', 'Sitemap': 'Site Haritası',
        'The Finest Quality': 'En İyi Kalite', 'PREMIUM SAFFRON': 'PREMIUM SAFRAN', 'Experience the true taste of luxury.': 'Lüksün gerçek tadını yaşayın.', 'Exporting Worldwide': 'Dünya Çapında İhracat', 'PERSIAN PISTACHIO': 'FARS FISTIĞI', 'Hand-picked and premium quality.': 'Özenle seçilmiş ve birinci sınıf kalite.', 'Palace Karimi': 'Palace Karimi', 'YOUR TRUSTED PARTNER': 'GÜVENİLİR ORTAĞINIZ', 'Providing the best agricultural products.': 'En iyi tarım ürünlerini sunuyoruz.',
        'Follow us on social media for the latest updates and news!': 'En son güncellemeler ve haberler için bizi sosyal medyada takip edin!',
        'Experience a secure purchase with the top exporter of authentic Iranian products': 'Otantik İran ürünlerinin en iyi ihracatçısı ile güvenli bir satın alma deneyimi yaşayın', 'Demand the best quality saffron and pistachio from us.': 'Bizden en kaliteli safran ve fıstığı talep edin.', 'Contact Experts': 'Uzmanlarla İletişime Geçin', 'or': 'veya', 'view products.': 'ürünleri görüntüleyin.', 'Palace Karimi is a brand that is': 'Palace Karimi', 'Authentic': 'Otantik', 'High Quality': 'Yüksek Kaliteli', 'Global': 'Küresel', 'and a secure choice for export.': 'bir markadır ve ihracat için güvenli bir seçimdir.', 'With years of experience in cultivation, processing, and exporting the finest Iranian saffron and pistachio, we offer quality and authenticity to global markets. All our products are packaged and shipped with international standards.': 'En iyi İran safranı ve fıstığının yetiştirilmesi, işlenmesi ve ihraç edilmesinde yılların verdiği tecrübe ile küresel pazarlara kalite ve özgünlük sunuyoruz. Tüm ürünlerimiz uluslararası standartlarda paketlenip sevk edilmektedir.',
        'Experience the pinnacle of luxury with Palace Karimi': 'Palace Karimi ile lüksün zirvesini yaşayın', 'Consultation': 'Danışma',
        'Harvesting': 'Hasat', 'Processing': 'İşleme', 'Packaging': 'Paketleme', 'Global Export': 'Küresel İhracat',
        'New': 'Yeni', 'View Details': 'Detayları Göster', 'No products available.': 'Gösterilecek ürün yok.',
        'Why Choose': 'Neden Seçmelisiniz', 'Palace Karimi?': 'Palace Karimi?', '100% Organic': '%100 Organik', 'Pure, natural products cultivated without harmful chemicals.': 'Zararlı kimyasallar olmadan yetiştirilen saf, doğal ürünler.', 'Premium Quality': 'Üstün Kalite', 'Export-grade saffron and pistachio carefully hand-picked.': 'İhracat sınıfı safran ve fıstık özenle elle toplanmıştır.', 'Luxury Packaging': 'Lüks Ambalaj', 'Elegant and secure packaging maintaining freshness and aroma.': 'Zarafet ve tazeliği koruyan şık ve güvenli ambalaj.', 'Lab Certified': 'Laboratuvar Sertifikalı', 'Rigorous laboratory testing for color, flavor, and purity.': 'Renk, lezzet ve saflık için titiz laboratuvar testleri.', 'Direct from Farms': 'Doğrudan Çiftliklerden', 'Sourced directly from the best Iranian agricultural lands.': 'Doğrudan en iyi İran tarım arazilerinden temin edilmiştir.', 'Wholesale Supply': 'Toptan Tedarik', 'Capability to fulfill bulk orders for businesses worldwide.': 'Dünya çapındaki işletmeler için toplu siparişleri karşılama kapasitesi.', '24/7 Support': '7/24 Destek', 'Dedicated customer service and consultation for our partners.': 'Ortaklarımız için özel müşteri hizmetleri ve danışmanlık.', 'Our Guarantees': 'Garantilerimiz', 'Authenticity Guarantee': 'Orijinallik Garantisi', 'We guarantee that all our saffron and pistachios are 100% authentic Persian products, free from any artificial additives or coloring.': 'Tüm safran ve fıstıklarımızın %100 otantik Fars ürünleri olduğunu, herhangi bir yapay katkı maddesi veya renklendirici içermediğini garanti ediyoruz.', 'International Standards': 'Uluslararası Standartlar', 'Our products are processed and packaged strictly according to international food safety and hygiene standards.': 'Ürünlerimiz uluslararası gıda güvenliği ve hijyen standartlarına sıkı sıkıya bağlı olarak işlenir ve paketlenir.', 'Custom White-Labeling': 'Özel Markalama', 'We offer exclusive custom packaging and white-labeling services for your brand to stand out in the global market.': 'Markanızın küresel pazarda öne çıkması için özel ambalaj ve beyaz etiketleme hizmetleri sunuyoruz.', 'We proudly export our products to': 'Ürünlerimizi gururla ihraç ediyoruz', 'Europe': 'Avrupa', 'Asia': 'Asya', 'Middle East': 'Orta Doğu', 'Trusted by leading international businesses and distributors worldwide.': 'Dünya çapında önde gelen uluslararası işletmeler ve distribütörler tarafından güvenilmektedir.'
    }
}

base_dir = os.path.abspath(os.path.dirname(__file__))
locale_dir = os.path.join(base_dir, 'locale')
os.makedirs(locale_dir, exist_ok=True)

for lang, trans_dict in translations.items():
    msg_dir = os.path.join(locale_dir, lang, 'LC_MESSAGES')
    os.makedirs(msg_dir, exist_ok=True)
    
    po_path = os.path.join(msg_dir, 'django.po')
    mo_path = os.path.join(msg_dir, 'django.mo')
    
    # Create PO file
    po = polib.POFile()
    po.metadata = {
        'Project-Id-Version': '1.0',
        'Language': lang,
        'MIME-Version': '1.0',
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Transfer-Encoding': '8bit',
    }
    
    for msgid, msgstr in trans_dict.items():
        entry = polib.POEntry(
            msgid=msgid,
            msgstr=msgstr
        )
        po.append(entry)
        
    po.save(po_path)
    po.save_as_mofile(mo_path)

print("All translation dictionaries generated and compiled successfully for Palace Karimi!")
