"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.contrib import staticfiles
from django.utils.translation import gettext_lazy as _
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i@rxx&-1(77k6hg2b)%k@myn31s)(xd_z6g9yd*v*-$1hyzy9u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'parler',
    'rosetta',
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'palace_db',
        'USER': 'postgres',
        'PASSWORD': '1',
        'HOST': '127.0.0.1',
        'PORT': '5433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True

LANGUAGES = [
    ('fa', _('Persian')),
    ('en', _('English')),
    ('ar', _('Arabic')),
    ('tr', _('Turkish')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

SITE_ID = 1


USE_TZ = True

PARLER_LANGUAGES = {
    1: (
        {'code': 'fa'},
        {'code': 'en'},
        {'code': 'ar'},
        {'code': 'tr'},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False,
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # --- تنظیمات برند و لوگو ---
    "site_title": "مدیریت کاخ کریمی",
    "site_header": "پنل مدیریت",
    "site_brand": "Palace Karimi",
    # آدرس لوگوی شما در پوشه static (نام فایل لوگوی خود را جایگزین کنید اگر متفاوت است)
    "site_logo": "img/logo.webp",
    "login_logo": "img/logo.webp",
    "site_logo_classes": "img-circle",  # لوگو را دایره‌ای می‌کند
    "site_icon": "img/favicon-32x32.png",  # آیکون تب مرورگر
    "welcome_sign": "به سیستم مدیریت محتوای کاخ کریمی خوش آمدید",
    "copyright": "Palace Karimi Ltd",

    # --- تنظیمات جستجو و منوها ---
    "search_model": ["catalog.Product", "catalog.ContactMessage"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "پیشخوان", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "مشاهده سایت", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "language_chooser": True,

    # --- آیکون‌های اختصاصی منو ---
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "catalog.Product": "fas fa-box-open",
        "catalog.Category": "fas fa-tags",
        "catalog.QualityGrade": "fas fa-gem",
        "catalog.PackagingType": "fas fa-box",
        "catalog.ProductVariant": "fas fa-cubes",
        "catalog.TieredPrice": "fas fa-hand-holding-usd",
        "catalog.ContactMessage": "fas fa-envelope-open-text",
        "catalog.ExchangeRate": "fas fa-money-check-alt",
    },

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "catalog.product": "single",
        "catalog.category": "single",
    },

    # --- معرفی فایل CSS اختصاصی ما ---
    "custom_css": "css/admin_rtl_fix.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "accent": "accent-success",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-success",

    # تنظیمات تم بر اساس داکیومنتی که فرستادی
    "theme": "flatly",  # تم پیش‌فرض برای حالت روز
    "dark_mode_theme": "darkly",  # تغییر خودکار به تم تاریک اگر سیستم کاربر روی Dark Mode باشد
}