# Generated by Django 5.2.15 on 2026-07-15 09:34

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'دسته\u200cبندی Translation'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام ارتباط با ما', 'verbose_name_plural': 'پیام\u200cهای کاربران'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['currency'], 'verbose_name': 'نرخ ارز', 'verbose_name_plural': 'نرخ\u200cهای ارز'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'verbose_name': 'نوع بسته\u200cبندی', 'verbose_name_plural': 'انواع بسته\u200cبندی'},
        ),
        migrations.AlterModelOptions(
            name='packagingtypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'نوع بسته\u200cبندی Translation'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'محصول Translation'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['weight_in_grams'], 'verbose_name': 'متغیر محصول', 'verbose_name_plural': 'متغیرهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='qualitygrade',
            options={'verbose_name': 'درجه کیفی', 'verbose_name_plural': 'درجات کیفی'},
        ),
        migrations.AlterModelOptions(
            name='qualitygradetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'درجه کیفی Translation'},
        ),
        migrations.AlterModelOptions(
            name='tieredprice',
            options={'ordering': ['min_qty'], 'verbose_name': 'قیمت پلکانی', 'verbose_name_plural': 'قیمت\u200cهای پلکانی'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وضعیت فعالیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='شناسه (Slug)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی کاربر'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده؟'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='مرورگر کاربر'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('AED', 'درهم امارات'), ('TRY', 'لیر ترکیه'), ('IRR', 'ریال ایران')], max_length=5, unique=True, verbose_name='کد ارز'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='نرخ تبدیل'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packagingtypetranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نوع بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.qualitygrade', verbose_name='درجه کیفی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نمایش در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین (Alt)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=catalog.models.get_image_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='تصویر اصلی است؟'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='full_description',
            field=models.TextField(verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیحات متا (SEO)'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='شناسه URL (اسلاگ)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='این متغیر به عنوان قیمت و ویژگی اصلی محصول نمایش داده می\u200cشود.', verbose_name='متغیر پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='moq',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل سفارش (MOQ)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.packagingtype', verbose_name='نوع بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='محصول مرتبط'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='کد کالا (SKU)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight_in_grams',
            field=models.PositiveIntegerField(verbose_name='وزن (گرم)'),
        ),
        migrations.AlterField(
            model_name='qualitygrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='qualitygrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='qualitygradetranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='درجه کیفی'),
        ),
        migrations.AlterField(
            model_name='tieredprice',
            name='max_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد'),
        ),
        migrations.AlterField(
            model_name='tieredprice',
            name='min_qty',
            field=models.PositiveIntegerField(verbose_name='حداقل تعداد'),
        ),
        migrations.AlterField(
            model_name='tieredprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (دلار)'),
        ),
        migrations.AlterField(
            model_name='tieredprice',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_prices', to='catalog.productvariant', verbose_name='متغیر محصول'),
        ),
    ]
