# Generated by Django 5.2.15 on 2026-07-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_categorytranslation_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='متن جایگزین برای سئو', max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text='آیا این عکس اصلی است؟')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variants/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='متن جایگزین برای سئو', max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text='آیا این عکس اصلی متغیر است؟')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
        ),
    ]
