# Generated by Django 5.2.15 on 2026-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='شناسه (Slug)'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='شناسه URL (اسلاگ)'),
        ),
    ]
