# Generated by Django 5.2.15 on 2026-07-04 13:26

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_variantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=catalog.utils.product_image_path),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to=catalog.utils.variant_image_path),
        ),
    ]
