# Generated by Django 5.2.15 on 2026-07-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productimage_image_alter_variantimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='e.g., USD, IRR, TRY, AED', max_length=3, unique=True)),
                ('rate_to_base', models.DecimalField(decimal_places=4, help_text='Exchange rate relative to base currency', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in base currency, e.g., USD', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
