# Generated by Django 5.2.15 on 2026-07-17 11:41

import catalog.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[300, 400], upload_to=catalog.models.get_image_upload_path, verbose_name='تصویر'),
        ),
    ]
