# Generated by Django 6.1 on 2026-08-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "مشترک خبرنامه",
                "verbose_name_plural": "مشترکین خبرنامه",
            },
        ),
    ]
