# Generated by Django 6.1 on 2026-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_newslettersubscriber_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="weight_in_grams",
            field=models.DecimalField(max_digits=100, decimal_places=2, verbose_name="وزن (گرم)"),
        ),
    ]
