# Generated by Django 5.2.15 on 2026-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_productvariant_weight_in_grams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="weight_in_grams",
            field=models.DecimalField(
                decimal_places=2, max_digits=100, verbose_name="وزن (گرم)"
            ),
        ),
    ]
